language: php

sudo: false

php:
  - 7
  - 7.1
  - 7.2
  - nightly

env: TMPDIR=/tmp USE_XDEBUG=false

branches:
  only:
    master

install:
  - phpenv rehash
  - travis_retry composer install --no-interaction --prefer-source

stages:
  - test
  - style check
  - phpstan analysis
  - test with coverage

before_script:
  - if [[ "$USE_XDEBUG" == false ]]; then phpenv config-rm xdebug.ini || return 0; fi

script:
  - composer test

jobs:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - stage: style check
      php: 7.1
      env: TMPDIR=/tmp USE_XDEBUG=false
      script:
        - composer style-check
    - stage: phpstan analysis
      php: 7.1
      env: TMPDIR=/tmp USE_XDEBUG=false
      script:
        - composer phpstan
    - stage: test with coverage
      php: 7.1
      env: TMPDIR=/tmp USE_XDEBUG=true CC_TEST_REPORTER_ID=8cbcfb40a4aff9431a0600f0a0ccb25ef4379d427443da50358d10f04a65f35f
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      script:
        - composer test-with-coverage
      after_success:
        - bash <(curl -s https://codecov.io/bash) -f ./clover.xml
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
